//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudurProjesi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MudurContext : DbContext
    {
        public MudurContext()
            : base("name=MudurContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_il> tbl_il { get; set; }
        public virtual DbSet<tbl_ilce> tbl_ilce { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }
}
